### ISSUE TITLE
Gulp not compatible with node >v9

### ISSUE THREAD

**Issue by arnaudmolo** [medialab/quinoa-story-player#25]
As stated in [this issue](https://github.com/gulpjs/gulp/issues/1829), gulp#3.9.1 is not compatible with node >9.
3 solutions : 
- nvm to switch betwin node versions (👎 )
- update gulp to use it's v4 (not officially published on npm yet) (😐)
- Kick gulp, just use webpack / Kotatsu

**Comment by Yomguithereal** [comment]
> Kick gulp, just use webpack / Kotatsu

Yes please :)
